---
title: "Reproduction, Life Expectancy"
author: "Pachia Lee"
date: "`r Sys.Date()`"
---
```{r}
library(tidyverse)
library(janitor)
library(lubridate)
library(RColorBrewer)
library(paletteer)
```

```{r}
#install.packages("RColorBrewer")
#install.packages("paletteer")
#install.packages("ggthemes")
```

Loading data
```{r}
ecosphere<- read_csv("ecosphere.csv") %>% clean_names()
```

```{r}
options(scipen = 999)
```



Structure of Data
```{r}
summary(ecosphere)
```

```{r}
names(ecosphere)
```
```{r}
display.brewer.pal(10,"PuBuGn") #sequential palette
```



##Create a plot that compares the top ten families and their population sizes
```{r}
ecosphere %>% 
  count(family)
```

```{r}
ecosphere %>% 
  filter(family=="Emberizidae")
```


##Create a plot that compares Emberizidae and life expectancy ranges
```{r}
ecosphere %>% 
  filter(family=="Emberizidae") %>% 
  group_by(life_expectancy) %>% 
  summarize(n=n())#number of observations in that variable
```

```{r}
ecosphere %>% 
  ggplot(aes(x=life_expectancy, fill=life_expectancy))+
  geom_bar(color="black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title = "Life Expectancy Ranges of the Family Emberizidae ")
```


```{r}
ecosphere %>% 
  filter(family=="Emberizidae") %>% 
  ggplot(aes(x = common_name, y = life_expectancy, fill=life_expectancy)) +
  geom_col() +
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title = "Life Expectancy Ranges of the Family Emberizidae ",
       x = "Common Name",
       y = "Life Expectancy") +
  theme(axis.text.x=element_text(size=12),axis.text.y = element_text(size = 6))+
  coord_flip()
```

```{r}
ecosphere %>% 
  filter(family=="Emberizidae") %>% 
  group_by(life_expectancy) %>% 
  summarize(n=n())
```

```{r}
ecosphere %>% 
  group_by(family) %>% 
  summarize(n=n())  %>% 
  top_n(5) %>% 
  arrange(desc(n))
  
```

```{r}
ecosphere %>% 
  filter(family==c("Anatidae", "Emberizidae", "Parulidae", "Scolopacidae", "Picidae", "Tyrannidae")) %>% 
  group_by(family) %>% 
  summarize(mean_eggs_family=mean(mean_eggs_per_clutch, na.rm=T))
```

```{r}
ecosphere %>% 
  filter(family==c("Anatidae", "Emberizidae", "Parulidae", "Scolopacidae", "Picidae", "Tyrannidae")) %>% 
  ggplot(aes(x=family, y=mean_eggs_per_clutch, fill=family))+
  geom_boxplot(color="black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title="Mean Eggs per Clutch in the Top Most Populated Families")
```

```{r}
ecosphere %>% 
  filter(family==c("Anatidae", "Emberizidae", "Parulidae")) %>% 
  ggplot(aes(x=mean_eggs_per_clutch, fill=family))+
  geom_density(alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")
  
```


```{r}
ecosphere %>%
  filter(family == "Emberizidae") %>%
  ggplot(aes(x = mean_eggs_per_clutch, fill = family)) +
  geom_density(color="black", alpha = 0.75, fill = "#cbc3e3") +
  labs(title = "Mean Eggs per Clutch of Emberizidae")
```

```{r}
ecosphere %>% 
  filter(family=="Emberizidae") %>% 
  ggplot(aes(x = common_name, y = mean_eggs_per_clutch , fill=mean_eggs_per_clutch)) +
  geom_col() +
  scale_color_continuous(palette = "PuBuGn")+ #I changed "scale_color_brewer" to "scale_color_continuous" bc that's what CHATGPT said
  coord_flip()+
  labs(title = "Mean Eggs per Clutch in the Family Emberizidae ",
       x = "Common Name",
       y = "Mean Eggs Per Clutch") +
  theme(axis.text.x=element_text(size=12),axis.text.y = element_text(size = 6))
```

```{r}
ecosphere %>% 
  filter(family==c("Emberizidae", "Parulidae", "Scolopacidae", "Picidae", "Tyrannidae")) %>% 
  group_by(family) %>% 
  summarize(mean_age_sexual_maturity=mean(mean_age_at_sexual_maturity , na.rm=T))
```

```{r}
ecosphere %>% 
  filter(family==c("Anatidae", "Emberizidae", "Parulidae")) %>% 
  ggplot(aes(x=mean_age_at_sexual_maturity , fill=family))+
  geom_density(alpha=0.5)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title="Mean Age of Sexual Maturity in the Top 3 Most Populated Families")
```


```{r}
ecosphere %>% 
  filter(family=="Emberizidae") %>% 
  ggplot(aes(x=mean_age_at_sexual_maturity , fill=family))+
  geom_density(alpha=0.5)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title="Mean Age of Sexual Maturity in Emberizidae Song Birds")
```

##Shiny App
```{r}
ui <- dashboardPage(
  dashboardHeader(title="Sex Composition by Wolve Population"),
  dashboardSidebar(disable=T),
  dashboardBody(
    fluidRow(
    box(width = 3,
        
        
    selectInput("x", "Select Population", choices =unique(wolves$pop)), hr()#gives some help with multiple observations
), 
  
  box(width=7,
      plotOutput("plot", width="600px", height="400px")
)
)
)
)
  
server <- function(input,output){
   session$onSessionEnded(stopApp) #automatically stop the app when we close it
  
  output$plot <- renderPlot({
  wolves %>% 
      filter(sex!="NA") %>% 
      filter(pop==inputs$x) %>% #filtr is the reactive part
      ffplot(aes(x=sex,fill=sex))+
      geom_bar()
    })
}

shinyApp(ui, server)
```











