---
title: "Reproduction, Life Expectancy"
author: "Pachia Lee"
date: "`r Sys.Date()`"
---

Loading data
```{r}
ecosphere<- read_csv("ecosphere.csv") %>%  clean_names()
```

Structure of Data
```{r}
summary(ecosphere)
```

```{r}
names(ecosphere)
```

##Create a plot that compares the top ten families and their population sizes
```{r}
ecosphere %>% 
  count(family)
```

```{r}
ecosphere_new<- ecosphere %>% 
  select(family, population_size, life_expectancy, mean_eggs_per_clutch, mean_age_at_sexual_maturity) %>% 
  filter(population_size!="NA")
```

```{r}
ecosphere_new %>% 
  count(family) %>% 
  arrange(desc(n)) %>% 
  slice_head(n = 10)
```

```{r}
names(ecosphere_new)
```

```{r}
options(scipen = 999)
```


```{r}
top_10_birds %>% 
  ggplot(aes(x=family, y=n, fill=family))+
  geom_col(alpha=0.5)+
  coord_flip()+
  labs(title="Family by Population Size",
       x="Family",
       y="Population Size")+
  theme(axis.text.x = element_text(size = 12),
        axis.text.y=element_text(size=12))
```


##Create a plot that compares each family and their 
```{r}
names(top_10_birds)
```



```{r}
ecosphere_new %>% 
  ggplot(aes(x=family, y=life_expectancy, fill=life_expectancy))+
  geom_col()+
  coord_flip()
```




