---
title: "Emberizidae"
author: "Jocelyn Morales"
date: "2024-03-11"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(janitor)
library(naniar)
library(RColorBrewer)
```


```{r}
ecosphere <- read.csv("ecosphere.csv", na = c("NA", "")) %>% 
  clean_names()
```

```{r}
emberizidae <- ecosphere %>% 
  filter(family=="Emberizidae")
```

```{r}
miss_var_summary(emberizidae)
```

```{r}
options(scipen=999)
```

```{r}
emberizidae %>%
  count(habitat)
```

```{r}
 emberizidae%>%
  filter(habitat != "NA" & habitat != "Various") %>% 
  count(habitat) %>% 
  ggplot(aes(x=reorder(habitat, n), y=n, fill = habitat))+
  geom_col(color = "black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title = "Number of Individuals in Each Habitat",
      x="Habitat",
      y= "# of Individuals")
```

```{r}
emberizidae %>% 
  count(migratory_strategy)
```

```{r}
emberizidae %>% 
  count(migratory_strategy) %>% 
  ggplot(aes(x=reorder(migratory_strategy, n), y=n, fill = migratory_strategy))+
  geom_col(color = "black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(title = "Number of Individuals with Preferred Migratory Strategy",
       x= "Migratory Strategy",
       y= "Count")
```

```{r}
emberizidae %>% 
  filter(habitat != "NA" & habitat != "Various") %>%
  ggplot(aes(x=urban_affiliate, y=winter_range_area, fill = migratory_strategy))+
  geom_boxplot(color = "black", alpha = 0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  scale_y_log10()+
  facet_wrap(~ habitat)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))
```

```{r}
emberizidae %>% 
  ggplot(aes(x=migratory_strategy, y=winter_range_area, fill = habitat))+
  geom_col (position = "dodge", color = "black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")+
  coord_flip()
```

```{r}
emberizidae %>% 
  ggplot(aes(x=urban_affiliate, fill = migratory_strategy))+
  geom_bar(position = "dodge", color = "black", alpha=0.75)+
  scale_fill_brewer(palette = "PuBuGn")
```

```{r}
emberizidae %>% 
  filter(habitat != "NA" & habitat != "Various") %>%
  ggplot(aes(x=reorder(habitat, winter_range_area), y=winter_range_area, fill = habitat))+
  geom_col(position = position_dodge(width = 0.8), color = "black", alpha = 0.75, width = 0.7)+
  scale_fill_brewer(palette = "PuBuGn")+
  labs(x="habitat")

```




